#!/bin/bash

docker-compose -f ./tests/services.yml up -d

ready_check="curl -XPUT -u 'admin:admin' 'localhost:9300/dummy_index' -H 'Content-Type: application/json' -d ' \
{ \
  \"settings\" : { \
    \"number_of_shards\" : 3, \
    \"number_of_replicas\" : 1 \
  } \
} \
' --fail"

while ! eval $ready_check
do
    { 
        echo "ElasticSearch is not ready..."
    } 1>&2
    sleep 5
done

python -m pytest tests/test_*.py -s
code=$?

docker-compose -f ./tests/services.yml down

exit $code

