{{- if .Values.opensearch.enabled }}
{{- $configRaw := .Values.securityFiles.configRaw | default (.Files.Get "files/opensearch-security/config.yml") -}}
{{- $internalUsersRaw := .Values.securityFiles.internalUsersRaw | default (.Files.Get "files/opensearch-security/internal_users.yml") -}}
{{- $rolesRaw := .Values.securityFiles.rolesRaw | default (.Files.Get "files/opensearch-security/roles.yml") -}}
{{- $rolesMappingRaw := .Values.securityFiles.rolesMappingRaw | default (.Files.Get "files/opensearch-security/roles_mapping.yml") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cogstack-opensearch.fullname" . }}-opensearch-security
  labels:
    {{- include "cogstack-opensearch.labels" . | nindent 4 }}
data:
  config.yml: |
{{ $configRaw | indent 4 }}
  internal_users.yml: |
{{ $internalUsersRaw | indent 4 }}
  roles.yml: |
{{ $rolesRaw | indent 4 }}
  roles_mapping.yml: |
{{ $rolesMappingRaw | indent 4 }}
{{- end }}
