{{- if .Values.opensearch.enabled }}
{{- $opensearchConfigRaw := .Values.configFiles.opensearchRaw | default (.Files.Get "files/opensearch.yml") -}}
{{- $log4jRaw := .Values.configFiles.log4jRaw | default (.Files.Get "files/log4j2.properties") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cogstack-opensearch.fullname" . }}-opensearch-config
  labels:
    {{- include "cogstack-opensearch.labels" . | nindent 4 }}
data:
  opensearch.yml: |
{{ $opensearchConfigRaw | indent 4 }}
  log4j2.properties: |
{{ $log4jRaw | indent 4 }}
{{- end }}
