{{- if .Values.envFile.raw }}
{{- $envData := include "cogstack-opensearch.parsedEnvFile" . | fromYaml | default (dict) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cogstack-opensearch.envConfigMapName" . }}
  labels:
    {{- include "cogstack-opensearch.labels" . | nindent 4 }}
data:
  {{- toYaml $envData | nindent 2 }}
{{- end }}
