{{- if and .Values.credentials.create (not .Values.credentials.existingSecret) (or .Values.opensearch.enabled .Values.dashboards.enabled) }}
{{- $usersData := include "cogstack-opensearch.parsedUsersEnvFile" . | fromYaml | default (dict) -}}
{{- $adminPassword := .Values.credentials.adminPassword -}}
{{- if hasKey $usersData "OPENSEARCH_INITIAL_ADMIN_PASSWORD" -}}
{{- $adminPassword = index $usersData "OPENSEARCH_INITIAL_ADMIN_PASSWORD" -}}
{{- end -}}
{{- $kibanaUser := .Values.credentials.kibanaUser -}}
{{- if hasKey $usersData "KIBANA_USER" -}}
{{- $kibanaUser = index $usersData "KIBANA_USER" -}}
{{- end -}}
{{- $kibanaPassword := .Values.credentials.kibanaPassword -}}
{{- if hasKey $usersData "KIBANA_PASSWORD" -}}
{{- $kibanaPassword = index $usersData "KIBANA_PASSWORD" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cogstack-opensearch.credentialsSecretName" . }}
  labels:
    {{- include "cogstack-opensearch.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.opensearch.enabled }}
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: {{ $adminPassword | quote }}
  {{- end }}
  {{- if .Values.dashboards.enabled }}
  KIBANA_USER: {{ $kibanaUser | quote }}
  KIBANA_PASSWORD: {{ $kibanaPassword | quote }}
  {{- end }}
{{- end }}
