version: '3.5'

#---------------------------------------------------------------------------#
#                                                                           #
# This docker-compose override files overrides the used service ports       #
#  and routing using NGINX in case when not binding ports to localhost      #
#                                                                           #
# It also overrides security configuration (disable use of SSL certs)       #
#                                                                           #
# Additional ElasticSearch nodes can be specified here                      #
#                                                                           #
#---------------------------------------------------------------------------#


#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:

#---------------------------------------------------------------------------#
# Postgres container with sample data                                       #
#---------------------------------------------------------------------------#
  samples-db:
    #ports:
    # <host:container> expose the postgres DB to host for debugging purposes
    #  - 5555:5432
    expose:
      - 5432


#---------------------------------------------------------------------------#
# NLP Service related containers                                            #
#---------------------------------------------------------------------------#
  nlp-gate-bioyodie:
    #ports:
    #  - "8095:8095"
    expose:
       - 8095

  nlp-medcat-umls:
    #ports:
      #- "8096:5000"
    expose:
      - 5000

  nlp-medcat-medmen:
    #ports:
    #  - "8096:5000"
    expose:
       - 5000


#---------------------------------------------------------------------------#
# ElasticSearch cluster                                                     #
#---------------------------------------------------------------------------#
  elasticsearch-1:
    environment:
      - discovery.type=single-node
      # - discovery.type=zen
      - opendistro_security.ssl.http.enabled=false
    #ports:
      #- 9200:9200
      #- 9600:9600
    expose:
      - 9200
      - 9600


#---------------------------------------------------------------------------#
# Kibana webapp                                                             #
#---------------------------------------------------------------------------#
  kibana:
    env_file: ./security/es_kibana_user.env
    environment:
      SERVER_SSL_ENABLED: "false"
    depends_on:
      - elasticsearch-1
    #ports:
      #- 5601:5601
    expose:
      - 5601


#---------------------------------------------------------------------------#
# NiFi webapp                                                               #
#---------------------------------------------------------------------------#
  nifi:
    expose:
      - 8080
      - 10000 # needed for site-to-site functionality 


#---------------------------------------------------------------------------#
# NGINX reverse-proxy                                                       #
#---------------------------------------------------------------------------#
  nginx:
    image: nginx:1.13.1-alpine
    restart: always
    depends_on:
      - nifi
      - kibana
      - elasticsearch-1
    ports:
      #- "5601:5601"
      #- "8081:8080"
      #- "8081:80"
      - "8080:8080"
      - "9200:9200"
      - "5601:5601"
    volumes:
      # mapping the proper timezone
      #- /etc/timezone:/etc/timezone:ro
      # mapping nginx config
      - ./services/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/auth/.htpasswd:/etc/apache2/.htpasswd:ro
    networks:
      - esnet
      - cognet
      - public


#---------------------------------------------------------------------------#
# Docker named volumes                                                      #
#---------------------------------------------------------------------------#
#volumes:
#  elasticsearch-vol-2:
#    driver: local
#  elasticsearch-vol-3:
#    driver: local


#---------------------------------------------------------------------------#
# Docker networks.                                                          #
#---------------------------------------------------------------------------#
networks:
  public:
    driver: bridge
