source:
  es:
    hosts: ["http://elasticsearch-1:9200"]
    index-name: 'cogstack_observations_view'
#    security:
#      ca-certs-path: '/app/config/root-ca.pem'
#      client-cert-path: '/app/config/client.pem'
#      client-key-path: '/app/config/client.key'

sink:
  es:
    hosts: ["http://elasticsearch-1:9200"]
    index-name: 'cogstack_atomic_annotations'
#    security:
#      ca-certs-path: "/app/config/root-ca.pem"
#      client-cert-path: "/app/config/client.pem"
#      client-key-path: "/app/config/client.key"

nlp-service:
  endpoint-url: 'http://nlp-gate-bioyodie:8095/api/process'

mapping:
  source:
    text-field: 'document_content'
    docid-field: 'document_id'
    persist-fields:
      - 'encounter_id'
      - 'patient_id'
      - 'observation_id'
      - 'encounter_start'
      - 'encounter_end'
    batch:
      date-field: 'encounter_start'
      date-format: 'yyyy-MM-dd'
      date-start: '1900-01-01'
      date-end: '2050-01-01'
  sink:
    split-index-by-field: ''

