# application configuration
#
application:
  version: 0.3.1

# general spring boot and server configuration
#
server:
  port: 8090
  tomcat:
    threads:
      max: 16

spring:
  servlet:
    multipart.max-file-size: 32768MB
    multipart.max-request-size: 32768MB
    multipart.file-size-threshold: 16384MB
    multipart.enabled: true

# tika configuration
#
tika:
  parsers:
    tesseract-ocr:
      language: eng
      timeout: 1200
      enable-image-processing: true
      apply-rotation: false
      # resize valid range:100-900, DEFAULT is 900, IMPORTANT: must be set in increments of 100
      resize: 100
      # density valid range:150-1200, DEFAULT IS 300
      density: 300
      depth: 16
      filter: "triangle"

    pdf-ocr-parser:
      ocr-only-strategy: false
      min-doc-text-length: 1
      min-doc-byte-size: 100
      apply-rotation: false
      ocr-detect-angles: false
      # dpi valid range: 0->inf, default from Tika is 300
      ocr-dpi: 200
      use-legacy-ocr-parser-for-single-page-doc: false

    post-ocr:
      output-encoding: "UTF-8"
      # if this is set to true, the output text will be UTF-8 compliant, all other chars are removed
      enforce-encoding-output: true

    legacy-pdf-parser:
      image-magick:
        timeout: 1200
      tesseract-ocr:
        timeout: 1200
      min-doc-text-length: 10
  bulk:
    num-consumers: 8

# documents processing configuration
#
processing:
  use-legacy-tika-processor-as-default: false
  fail-on-empty-files: false
  fail-on-non-document-types: false

logging:
  level:
    root: DEBUG
    tika.processor: DEBUG
    org.springframework.web: DEBUG
    service.controller: DEBUG
    org.hibernate: DEBUG
  file:
    path: "./"
    name: "app.log"
