{{- if and .Values.sensitiveConfig.create (not .Values.sensitiveConfig.existingSecret) }}
{{- $certData := include "cogstack-nifi.parsedCertificatesEnvFile" . | fromYaml | default (dict) -}}
{{- $usersData := include "cogstack-nifi.parsedUsersEnvFile" . | fromYaml | default (dict) -}}
{{- $sensitivePropsKey := required "NIFI_SENSITIVE_PROPS_KEY must be set in certificatesEnvFile" (index $certData "NIFI_SENSITIVE_PROPS_KEY") -}}
{{- $keystorePassword := required "NIFI_KEYSTORE_PASSWORD must be set in certificatesEnvFile" (index $certData "NIFI_KEYSTORE_PASSWORD") -}}
{{- $keyPassword := $keystorePassword -}}
{{- if hasKey $certData "NIFI_KEY_PASSWORD" -}}
{{- $keyPassword = index $certData "NIFI_KEY_PASSWORD" -}}
{{- end -}}
{{- $truststorePassword := required "NIFI_TRUSTSTORE_PASSWORD must be set in certificatesEnvFile" (index $certData "NIFI_TRUSTSTORE_PASSWORD") -}}
{{- $singleUserUsername := required "NIFI_SINGLE_USER_CREDENTIALS_USERNAME must be set in usersEnvFile" (index $usersData "NIFI_SINGLE_USER_CREDENTIALS_USERNAME") -}}
{{- $singleUserPassword := required "NIFI_SINGLE_USER_CREDENTIALS_PASSWORD must be set in usersEnvFile" (index $usersData "NIFI_SINGLE_USER_CREDENTIALS_PASSWORD") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cogstack-nifi.sensitiveSecretName" . }}
  labels:
    {{- include "cogstack-nifi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.sensitiveConfig.keys.sensitivePropsKey }}: {{ $sensitivePropsKey | quote }}
  {{ .Values.sensitiveConfig.keys.keystorePassword }}: {{ $keystorePassword | quote }}
  {{ .Values.sensitiveConfig.keys.keyPassword }}: {{ $keyPassword | quote }}
  {{ .Values.sensitiveConfig.keys.truststorePassword }}: {{ $truststorePassword | quote }}
  {{ .Values.sensitiveConfig.keys.singleUserUsername }}: {{ $singleUserUsername | quote }}
  {{ .Values.sensitiveConfig.keys.singleUserPassword }}: {{ $singleUserPassword | quote }}
{{- end }}
