FROM jupyterhub/singleuser:latest

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTPS_PROXY
ENV NO_PROXY=$NO_PROXY
ENV http_proxy=$HTTP_PROXY
ENV https_proxy=$HTTPS_PROXY
ENV no_proxy=$NO_PROXY

USER root

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y \
    gnupg \
    libssl-dev \
    wget \
    curl \
    gnupg \
    gnupg-agent \
    dirmngr \
    ca-certificates \
    apt-transport-https \
    software-properties-common \
    fonts-dejavu \
    build-essential \
    python3-dev \
    python3-pip \
    unixodbc \
    unixodbc-dev \
    r-cran-rodbc \
    gfortran \
    gcc \
    git \
    ssh \
    jq \
    htop \
    libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 \
    libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 \
    r-base 

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/21.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

# install remaining packages
RUN apt-get update && apt-get upgrade -y
RUN apt-get -y --no-install-recommends install unixodbc unixodbc-dev odbcinst
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18
RUN ACCEPT_EULA=Y apt-get install -y mssql-tools18
RUN echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc

RUN conda update conda
RUN conda install --quiet --yes \
    elasticsearch \
    psycopg2 \
    pyodbc \
    pymssql

RUN conda clean --all -f -y

RUN fix-permissions $CONDA_DIR && fix-permissions /home/$NB_USER

# deps for psycopg2
RUN apt-get install -y postgresql-server-dev-all python3 python3-pip python3-dev python3.9-dev python3-all-dev ssl-cert --no-install-recommends 

RUN pip3 install --upgrade pip
RUN pip3 install setuptools wheel virtualenv

# jupyterhub stuff
RUN pip3 install ipywidgets jupyter jupyterhub jupyterlab jupyterlab-git importlib_metadata
RUN pip3 install jupyterlab_widgets jupyter_contrib_core jupyter_contrib_nbextensions jupyter-server-proxy fastbook
RUN pip3 install dockerspawner jupyterhub-firstuseauthenticator jupyterhub-systemdspawner jupyterhub-jwtauthenticator jupyterhub-client jupyterhub-kerberosauthenticator 
RUN pip3 install jupyterhub-nanowireauthenticator jupyterhub-ldapauthenticator jupyterhub-kubespawner jupyterhub-nativeauthenticator

# extra packages for DB connections & utilities (charts, data formats, and other useful tools such as neo4j)
RUN pip3 install virtualenv pytesseract ipyparallel py7zr cython isort html2text jsoncsv simplejson detect wheel nltk keras bokeh seaborn matplotlib graphviz plotly tqdm 
RUN pip3 install pymssql mysql-connector-python cx-Oracle dataclasses numpy matplotlib pandas dill jsonpickle jsonext psycopg2 psycopg2-binary pyodbc
RUN pip3 install dvc flask GitPython elasticsearch opensearch-py neo4j --ignore-installed PyYAML 

# XNAT
RUN pip3 install xnat

# medcat & models
RUN pip3 install medcat && python3 -m spacy download en_core_web_md && \
    pip3 install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_md-0.4.0.tar.gz && \
    pip3 install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.4.0/en_core_sci_lg-0.4.0.tar.gz

COPY r_kernel_install.sh /etc/jupyterhub/

RUN Rscript /etc/jupyterhub/r_kernel_install.sh


# create jupyterhub shared folder

RUN mkdir -p /home/jovyan/scratch
RUN chmod -R 777 /home/jovyan/scratch
RUN chmod g+s /home/jovyan/scratch
RUN chmod 0777 /home/jovyan/scratch

RUN mkdir /home/$NB_USER/notebooks

# copy scripts and config files
COPY config/jupyter_notebook_config.py /home/jovyan/.jupyter/

# copy notebooks
COPY notebooks /home/jovyan/work/

# clean up
RUN apt-get autoremove -y

WORKDIR /home/jovyan
USER jovyan

# Configure container startup
ENTRYPOINT ["tini", "-g", "--"]

CMD ["jupyterhub-singleuser"]