FROM jupyterhub/singleuser:3

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG NO_PROXY
ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV HTTP_PROXY=$HTTP_PROXY
ENV HTTPS_PROXY=$HTTPS_PROXY
ENV NO_PROXY=$NO_PROXY
ENV http_proxy=$HTTP_PROXY
ENV https_proxy=$HTTPS_PROXY
ENV no_proxy=$NO_PROXY

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_PRIORITY=critical

USER root

RUN apt-get update && apt-get upgrade -y && \
     apt-get install -y software-properties-common

# add extra repos
RUN apt-add-repository multiverse && \
    apt-add-repository universe && \
    add-apt-repository ppa:graphics-drivers/ppa && \
    apt-get update && apt-get upgrade -y 

# Add latest ubuntu repos to sources.list
RUN echo "deb http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse" | tee -a /etc/apt/sources.list
RUN echo "deb-src http://archive.ubuntu.com/ubuntu/ jammy main restricted universe multiverse" | tee -a /etc/apt/sources.list
RUN echo "deb http://archive.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse" | tee -a /etc/apt/sources.list
RUN echo "deb-src http://archive.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse" | tee -a /etc/apt/sources.list
RUN echo "deb http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse" | tee -a /etc/apt/sources.list
RUN echo "deb-src http://archive.ubuntu.com/ubuntu/ jammy-backports main restricted universe multiverse" | tee -a /etc/apt/sources.list
RUN echo "deb http://archive.canonical.com/ubuntu/ jammy partner" | tee -a /etc/apt/sources.list
RUN echo "deb-src http://archive.canonical.com/ubuntu/ jammy partner" | tee -a /etc/apt/sources.list

# remove newer python version, freeze other versions for max compatibility before updates
# RUN apt-mark hold python3.10 python3.9 python3.8 python3 python3-gi python3-dev python3-distutils python3-lib2to3
# RUN apt-get purge --auto-remove python3.10

# run updates
RUN apt-get update && apt-get upgrade -y && \
    apt-get --force-yes -o Dpkg::Options::="--force-confold" --force-yes -o Dpkg::Options::="--force-confdef" -fuy full-upgrade && \
    apt-get autoremove -y && \
    apt-get install -y \
    gnupg \
    ssl-cert \ 
    libevent-dev \
    python3-dev \
    python3.10-dev \
    python3-all-dev \
    python3-pip \
    libxml2-dev \
    libbz2-dev \
    libxslt1-dev \
    zlib1g-dev \
    libssl-dev \
    wget \
    curl \
    gnupg-agent \
    dirmngr \
    ca-certificates \
    apt-transport-https \
    apt-utils \
    fonts-dejavu \
    nano \
    iputils-ping \
    cmake \
    make \
    build-essential \
    unixodbc \
    unixodbc-dev \
    r-cran-rodbc \
    gfortran \
    gcc \
    g++ \
    git \
    ssh \
    jq \
    htop \
    libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 \
    libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 \
    r-base

RUN apt-get update && apt-get upgrade -y 

# Microsoft repos
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/21.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list >> /etc/apt/sources.list.d/mssql-release.list

# install remaining packages
RUN apt-get update && apt-get upgrade -y
RUN apt-get -y --no-install-recommends install unixodbc unixodbc-dev odbcinst
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18
RUN ACCEPT_EULA=Y apt-get install -y mssql-tools18
RUN echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc

RUN conda update conda
RUN conda install --quiet --yes \
    elasticsearch \
    psycopg2 \
    pyodbc \
    pymssql

RUN conda clean --all -f -y

RUN fix-permissions $CONDA_DIR && fix-permissions /home/$NB_USER

# deps for psycopg2
RUN apt-get install -y postgresql-server-dev-all --no-install-recommends 

# update pip and install basic utilities
RUN pip3 install --upgrade pip
RUN pip3 install setuptools wheel virtualenv

# jupyterhub stuff
RUN pip3 install ipywidgets jupyter jupyterhub jupyterlab jupyterlab-git importlib_metadata
RUN pip3 install jupyterlab_widgets jupyter_contrib_core jupyter_contrib_nbextensions jupyter-server-proxy fastbook
RUN pip3 install docker docker-compose dockerspawner jupyterhub-firstuseauthenticator jupyterhub-systemdspawner jupyterhub-jwtauthenticator jupyterhub-client jupyterhub-kerberosauthenticator 
RUN pip3 install jupyterhub-nanowireauthenticator jupyterhub-ldapauthenticator jupyterhub-kubespawner jupyterhub-nativeauthenticator

# extra packages for DB connections & utilities (charts, data formats, and other useful tools such as neo4j)
RUN pip3 install pytesseract ipyparallel py7zr cython isort html2text jsoncsv simplejson detect wheel nltk keras bokeh seaborn matplotlib graphviz plotly tqdm 
RUN pip3 install pymssql mysql-connector-python cx-Oracle dataclasses numpy matplotlib pandas dill jsonpickle jsonext psycopg2 psycopg2-binary pyodbc
RUN pip3 install dvc flask GitPython elasticsearch opensearch-py neo4j --ignore-installed PyYAML 

# XNAT
RUN pip3 install xnat

# medcat & models
RUN pip3 install -U spacy click torch thinc

# Get the spacy model
#ARG SPACY_MODELS="en_core_web_sm en_core_web_md en_core_web_lg"
#RUN for spacy_model in ${SPACY_MODELS}; do python3 -m spacy download $spacy_model; done

RUN pip3 install medcat

# install R and other dependencies
COPY r_kernel_install.sh /etc/jupyterhub/
RUN Rscript /etc/jupyterhub/r_kernel_install.sh

# create jupyterhub shared folder
RUN mkdir -p /home/jovyan/scratch
RUN chmod -R 777 /home/jovyan/scratch
RUN chmod g+s /home/jovyan/scratch
RUN chmod 0777 /home/jovyan/scratch

# copy scripts and config files
COPY config/jupyter_notebook_config.py /home/jovyan/.jupyter/

# copy notebooks
COPY notebooks /home/jovyan/work/

# clean up
RUN apt-get autoremove -y

WORKDIR /home/jovyan
USER jovyan

# Configure container startup
ENTRYPOINT ["tini", "-g", "--"]

CMD ["jupyterhub-singleuser"]