#----------------------
# single node cluster conf
#----------------------
## Use single node discovery in or https
discovery.type: zen

#----------------------
# multi node cluster conf
#----------------------
network.host: 0.0.0.0
discovery.seed_hosts: ["elasticsearch-1", "elasticsearch-2"]
http.port: 9200
cluster.initial_master_nodes: ["es01", "es02"]

#----------------------
# X-Pack features
# disabled by default when using '-oss' images
# need to be disabled manually when using standard images from elastic
#----------------------
xpack.license.self_generated.type: trial
xpack.security.enabled: true

xpack.security.transport.ssl.verification_mode: certificate 
xpack.security.http.ssl.verification_mode: certificate
xpack.security.transport.ssl.client_authentication: optional

xpack.security.http.ssl.enabled: true
xpack.security.transport.ssl.enabled : true

#xpack.security.transport.ssl.keystore.path: esnode.p12
#xpack.security.transport.ssl.keystore.type: PKCS12
#xpack.security.transport.ssl.truststore.path: esnode.p12
#xpack.security.transport.ssl.truststore.type: PKCS12

xpack.security.http.ssl.key: esnode.key
xpack.security.http.ssl.certificate: esnode.crt
xpack.security.http.ssl.certificate_authorities: ["root-ca.crt"]  
xpack.security.transport.ssl.key: esnode.key
xpack.security.transport.ssl.certificate: esnode.crt
xpack.security.transport.ssl.certificate_authorities: ["root-ca.crt"]
