FROM docker.elastic.co/elasticsearch/elasticsearch:8.19.6

RUN bin/elasticsearch-plugin install --batch https://github.com/alexklibisz/elastiknn/releases/download/8.19.0.0/elastiknn-8.19.0.0.zip

RUN bin/elasticsearch-plugin install --batch analysis-icu

COPY ./sysctl.conf /etc/

