FROM docker.elastic.co/elasticsearch/elasticsearch:8.18.3

RUN bin/elasticsearch-plugin install --batch https://github.com/alexklibisz/elastiknn/releases/download/8.18.3.0/elastiknn-8.18.3.0.zip

RUN bin/elasticsearch-plugin install --batch analysis-icu

COPY ./sysctl.conf /etc/