# Mapped on top-level of 2001 NHS Data Dictionary; https://datadictionary.nhs.uk/data_elements/ethnic_category.html 
ethnicity_map = {'algerian': 'black',
 'any other group': 'other',
 'asian and chinese': 'asian',
 'bangladeshi': 'asian',
 'black african': 'black',
 'black british': 'black',
 'black': 'black',
 'british': 'white',
 'caribbean': 'black',
 'asian': 'asian',
 'chinese': 'asian',
 'cypriot (part nt st)': 'white',
 'ecuadorian': 'other',
 'english': 'white',
 'ethiopian': 'black',
 'filipino': 'asian',
 'ghanaian': 'black',
 'american': "unknown",
 'greek cypriot': 'white',
 'indian/british india': 'asian',
 'iranian': 'other',
 'italian': 'white',
 'dominican': 'other',
 'mixed black': 'black',
 'mixed caribbean': 'black',
 'nigerian': 'black',
 'not given': 'unknown',
 'not specified': 'unknown',
 'not stated': 'unknown',
 'other asian backgrou': 'asian',
 'other asian unspecif': 'asian',
 'other black backgrou': 'black',
 'other black unspecif': 'black',
 'other ethnic group': 'other',
 'other latin american': 'other',
 'other white back gro': 'white',
 'other white unspecif': 'white',
 'other white/mixed eu': 'white',
 'pakistani/british pa': 'asian',
 'portuguese': 'white',
 'somali': 'black',
 'spanish': 'white',
 'mexican': 'other',
 'puerto rican': 'other',
 'sri lankan': 'asian',
 'sudanese': 'black',
 'turkish': 'other',
 'ugandan': 'black',
 'vietnamese': 'asian',
 'white irish': 'white',
 'former ussr rep': 'white',
 'polish': 'white',
 'iraqi': 'other',
 'albanian': 'other',
 'columbian': 'other',
 'scottish': 'white',
 'not stated': 'unknown',
 'other mixed backgrou': 'mixed',
 'welsh': 'white',
 'british asian': 'asian',
 'caribbean asian': 'asian',
 'eritrean': 'black',
 'turkish cypriot': 'other',
 'sinhalese': 'asian',
 'white and asian': 'asian',
 'other mixed': 'mixed',
 'mixed asian': 'asian',
 'greek': 'white',
 'white': 'white',
 'arab': 'other',
 'multiple codes': 'multiple codes',
 'irish': 'white',
 'japanese': 'asian',
 'middle east': 'other',
 'croatian': 'white',
 'hispanic': 'other',
 'black and asian': 'mixed',
 'black and white': 'mixed'}

# Mapped on bottom-level of 2001 NHS Data Dictionary; https://datadictionary.nhs.uk/data_elements/ethnic_category.html 
ethnicity_map_detail = {'algerian': 'black or black british - african',
 'any other group': 'other ethnic groups - any other ethnic group',
 'asian and chinese': 'other ethnic groups - chinese',
 'bangladeshi': 'asian or asian british - pakistani',
 'black african': 'black or black british - african',
 'black british': 'black or black british - any other black background',
 'british': 'white - british',
 'caribbean': 'black or black british - caribbean',
 'chinese': 'other ethnic groups - chinese',
 'cypriot (part nt st)': 'white - any other white background',
 'ecuadorian': 'other ethnic groups - any other ethnic group',
 'english': 'white - british',
 'ethiopian': 'black or black british - african',
 'filipino': 'asian or asian british - any other asian background',
 'ghanaian': 'black or black british - african',
 'greek cypriot': 'white - any other white background',
 'indian/british india': 'asian or asian british - indian',
 'iranian': 'other ethnic groups - any other ethnic group',
 'italian': 'white - any other white background',
 'mixed black': 'black or black british - any other black background',
 'mixed caribbean': 'black or black british - caribbean',
 'nigerian': 'black or black british - african',
 'not given': 'not stated',
 'not specified': 'not stated',
 'not stated': 'not stated',
 'other asian backgrou': 'asian or asian british - any other asian background',
 'other asian unspecif': 'asian or asian british - any other asian background',
 'other black backgrou': 'black or black british - any other black background',
 'other black unspecif': 'black or black british - any other black background',
 'other ethnic group': 'other ethnic groups - any other ethnic group',
 'other latin american': 'other ethnic groups - any other ethnic group',
 'other white back gro': 'white - any other white background',
 'other white unspecif': 'white - any other white background',
 'other white/mixed eu': 'white - any other white background',
 'pakistani/british pa': 'asian or asian british - pakistani',
 'portuguese': 'white - any other white background',
 'somali': 'black or black british - african',
 'spanish': 'white - any other white background',
 'sri lankan': 'asian or asian british - any other asian background',
 'sudanese': 'black or black british - african',
 'turkish': 'other ethnic groups - any other ethnic group',
 'ugandan': 'black or black british - african',
 'vietnamese': 'other ethnic groups - any other ethnic group',
 'white irish': 'white - irish',
 'former ussr rep': 'white - any other white background',
 'polish': 'white - any other white background',
 'iraqi': 'other ethnic groups - any other ethnic group',
 'albanian': 'white - any other white background',
 'columbian': 'other ethnic groups - any other ethnic group',
 'scottish': 'white - british',
 'not stated': 'not stated',
 'other mixed backgrou': 'mixed - any other mixed background',
 'welsh': 'white - british',
 'british asian': 'asian or asian british - any other asian background',
 'caribbean asian': 'mixed - any other mixed background',
 'eritrean': 'black or black british - african',
 'turkish cypriot': 'other ethnic groups - any other ethnic group',
 'sinhalese': 'asian or asian british - any other asian background',
 'white and asian': 'mixed - white and asian',
 'other mixed': 'mixed - any other mixed background',
 'mixed asian': 'mixed - any other mixed background',
 'greek': 'white - any other white background',
 'arab': 'other ethnic groups - any other ethnic group',
 'multiple codes': 'multiple codes',
 'irish': 'white - irish',
 'japanese': 'other ethnic groups - any other ethnic group',
 'middle east': 'other ethnic groups - any other ethnic group',
 'croatian': 'white - any other white background',
 'black and asian': 'mixed - white and asian',
 'black and white': 'mixed - any other mixed background'}