version: '3.5'

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:


#---------------------------------------------------------------------------#
# ElasticSearch cluster                                                     #
#---------------------------------------------------------------------------#
  elasticsearch-1:
    image: amazon/opendistro-for-elasticsearch:1.6.0
    container_name: cogstack-elasticsearch-1
    restart: always
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      # INFO: enable 'zen' for multi-node cluster
      # - discovery.type=zen
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      # INFO: set 'true' to enable SSL
      - opendistro_security.ssl.http.enabled=false
      #- opendistro_security.ssl.transport.enabled=false
    volumes:
      # mapping security config
      # INFO: uncomment below to add SSL keys
      #- ../security/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem:ro
      #- ../security/es-node1.pem:/usr/share/elasticsearch/config/esnode.pem:ro
      #- ../security/es-node1.key:/usr/share/elasticsearch/config/esnode.key:ro
      #- ../security/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml:ro
      #
      # INFO: ES configuration mapped via volume
      #- ../services/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # ES data persistence
      - elasticsearch-vol-1:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    expose:
      - 9600
    networks:
      - cognet


#---------------------------------------------------------------------------#
# Kibana webapp                                                             #
#---------------------------------------------------------------------------#
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.6.0
    container_name: cogstack-kibana
    restart: always
    #env_file: ./security/es_kibana_user.env
    environment:
      # INFO: use HTTPS instead of HTTP when enabled SSL
      ELASTICSEARCH_URL: http://elasticsearch-1:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch-1:9200
      # INFO: uncomment below to enable SSL keys
      SERVER_SSL_ENABLED: "false"
      #SERVER_SSL_KEY: /usr/share/kibana/config/kibana.key
      #SERVER_SSL_CERTIFICATE: /usr/share/kibana/config/kibana.pem
    depends_on:
      - elasticsearch-1
    #volumes:
      # mapping kibana config
      # INFO: uncomment below to add SSL keys
      #- ../security/root-ca.pem:/usr/share/kibana/config/root-ca.pem:ro
      #- ../security/kibana.pem:/usr/share/kibana/config/kibana.pem:ro
      #- ../security/kibana.key:/usr/share/kibana/config/kibana.key:ro
    ports:
      - "5601:5601"
    networks:
      - cognet


#---------------------------------------------------------------------------#
# Docker named volumes                                                      #
#---------------------------------------------------------------------------#
volumes:
  elasticsearch-vol-1:
    driver: local


#---------------------------------------------------------------------------#
# Docker networks.                                                          #
#---------------------------------------------------------------------------#
networks:
  cognet:
    name: cogstack-net
