version: '3.5'

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:


#---------------------------------------------------------------------------#
# Jupyter Hub                                                               #
#---------------------------------------------------------------------------#
  jupyter-hub:
    #image: lrog/cogstack-jupyter-hub:latest
    build: ../services/jupyter-hub/
    container_name: cogstack-nifi
    restart: always
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - "../services/jupyter-hub/notebooks:/home/jovyan/notebooks"
    ports:
      - "10000:8888"
    networks:
      - cognet


#---------------------------------------------------------------------------#
# Docker networks.                                                          #
#---------------------------------------------------------------------------#
networks:
  cognet:
    name: cogstack-net
