version: '3.5'

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:


#---------------------------------------------------------------------------#
# NLP Services containers                                                   #
#   * using example free models / resources                                 #
#---------------------------------------------------------------------------#
  nlp-medcat-medmen:
    image: cogstacksystems/medcat-service:latest
    container_name: cogstack-medcat-medmen
    restart: always
    # INFO: MedCAT configuration is specified via 'env' files
    env_file:
      - ../services/nlp-services/applications/medcat/config/env_app
      - ../services/nlp-services/applications/medcat/config/env_medcat
    environment:
      - APP_MODEL_NAME=medmen-demo
    # INFO: MedCAT models are mounted via volumes
    volumes:
      - ../services/nlp-services/applications/medcat/models/medmen/cdb.dat:/cat/models/cdb.dat:ro
      - ../services/nlp-services/applications/medcat/models/medmen/vocab.dat:/cat/models/vocab.dat:ro
    #expose:
    #  - 5000
    ports:
      - "5000:5000"
    networks:
      - cognet


#---------------------------------------------------------------------------#
# NLP Services containers                                                   #
#   * using internal models / resources                                     #
#---------------------------------------------------------------------------#
  nlp-medcat-snomed:
    image: cogstacksystems/medcat-service:latest
    container_name: cogstack-medcat-snomed
    restart: always
    env_file:
      - ../services/nlp-services/applications/medcat/config/env_app
      - ../services/nlp-services/applications/medcat/config/env_medcat
    environment:
      - APP_MODEL_NAME=snomed-mimic
    volumes:
      - ${RES_MEDCAT_SNOMED_PATH}/cdb.dat:/cat/models/cdb.dat:ro
      - ${RES_MEDCAT_SNOMED_PATH}/vocab.dat:/cat/models/vocab.dat:ro
    expose:
      - 5000
    networks:
      - cognet


#---------------------------------------------------------------------------#
# MedCAT Trainer                                                            #
#---------------------------------------------------------------------------#
  medcat-trainer-ui:
    image: cogstacksystems/medcat-trainer:latest
    container_name: cogstack-medcat-trainer-ui
    restart: always
    # INFO: MedCAT library config provided via env file
    env_file:
      - ../services/medcat-trainer/envs/env
    volumes:
      - medcat-api-media:/home/api/media
      - medcat-api-static:/home/api/static
      - medcat-api-db:/home/api/db
    expose:
      - "8000"
    command: /home/run.sh

  medcat-trainer-nginx:
    image: cogstacksystems/medcat-trainer-nginx:latest
    container_name: cogstack-medcat-trainer-nginx
    restart: always
    volumes:
      - ../services/medcat-trainer/nginx/sites-enabled:/etc/nginx/sites-enabled/:ro
      - medcat-api-media:/home/api/media
      - medcat-api-static:/home/api/static
    ports:
      - "8001:8000"
    depends_on:
      - medcat-trainer-ui


#---------------------------------------------------------------------------#
# Docker named volumes                                                      #
#---------------------------------------------------------------------------#
volumes:
  medcat-api-media:
    driver: local
  medcat-api-static:
    driver: local
  medcat-api-db:
    driver: local


#---------------------------------------------------------------------------#
# Docker networks.                                                          #
#---------------------------------------------------------------------------#
networks:
  cognet:
    name: cogstack-net
