version: '3.5'

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:


#---------------------------------------------------------------------------#
# NLP Services containers                                                   #
#   * using example free models / resources                                 #
#---------------------------------------------------------------------------#
  nlp-gate-drugapp:
    #image: cogstacksystems/nlp-rest-service-gate:latest
    build: ../services/nlp-services/applications/drug-app/
    container_name: cogstack-gate-drugapp
    restart: always
    volumes:
      # INFO: CogStack GATE runner configuration files
      - ../services/nlp-services/applications/drug-app/config:/app/nlp-service/config:ro
      - ../services/nlp-services/applications/drug-app/gate:/gate/app/drug-app:ro
    command: "bash /app/nlp-service/run.sh"
    #expose:
    #  - 8095
    ports:
      - "8095:8095"
    networks:
      - cognet


#---------------------------------------------------------------------------#
# NLP Services containers                                                   #
#   * using internal models / resources                                     #
#---------------------------------------------------------------------------#
  nlp-gate-bioyodie:
    image: cogstacksystems/nlp-rest-service-gate:latest
    container_name: cogstack-gate-bioyodie
    restart: always
    volumes:
      # INFO: CogStack GATE runner configuration files
      - ../services/nlp-services/applications/bio-yodie/config:/app/nlp-service/config:ro
      # TODO: properly set BioYODIE UMLS resources
      - ${RES_BIOYODIE_UMLS_PATH}:/gate/app/bioyodie/bio-yodie-resources:ro
    #command: "bash /app/nlp-service/run.sh"
    expose:
      - 8095
    networks:
      - cognet


#---------------------------------------------------------------------------#
# Docker networks.                                                          #
#---------------------------------------------------------------------------#
networks:
  cognet:
    name: cogstack-net
