version: '3.5'

#---------------------------------------------------------------------------#
# Used services                                                             #
#---------------------------------------------------------------------------#
services:


#---------------------------------------------------------------------------#
# Apache Tika documents processing service                                  #
#---------------------------------------------------------------------------#
  tika:
    image: cogstacksystems/tika-service:latest
    container_name: cogstack-tika
    restart: always
    # INFO: Tika pipeline-specific configuration is mounted via volume
    volumes:
      - ../services/tika-service/config:/app/config:ro
    expose:
      - 8090
    networks:
      - cognet


#---------------------------------------------------------------------------#
# Docker networks.                                                          #
#---------------------------------------------------------------------------#
networks:
  cognet:
    name: cogstack-net
