{{- if and .Values.cluster.enabled (not .Values.credentials.existingAppSecret) }}
{{- $usersData := include "cogstack-postgresql.parsedUsersEnvFile" . | fromYaml | default (dict) -}}
{{- $ownerName := "admin" -}}
{{- if .Values.cluster.ownerName -}}
{{- $ownerName = .Values.cluster.ownerName -}}
{{- else if hasKey $usersData "DATABASE_USER" -}}
{{- $ownerName = index $usersData "DATABASE_USER" -}}
{{- end -}}
{{- $ownerPassword := "admin" -}}
{{- if .Values.credentials.password -}}
{{- $ownerPassword = .Values.credentials.password -}}
{{- else if hasKey $usersData "DATABASE_PASSWORD" -}}
{{- $ownerPassword = index $usersData "DATABASE_PASSWORD" -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cogstack-postgresql.appSecretName" . }}
  labels:
    {{- include "cogstack-postgresql.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ $ownerName | quote }}
  password: {{ $ownerPassword | quote }}
{{- end }}
