# Some of these parameters are provided by the Docker environment variables
server.name: cogstack-kibana
server.host: "0.0.0.0"
server.port: 5601

telemetry.optIn: false
telemetry.enabled: false

# INFO: ES URL provided as docker parameter
elasticsearch.hosts: ${ELASTICSEARCH_HOSTS}
elasticsearch.ssl.verificationMode: certificate
elasticsearch.ssl.certificateAuthorities: ["config/root-ca.crt"]

# WARNING: revise all the lines below before you go into production
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]

server.ssl.enabled: true
server.ssl.certificate: "config/esnode1.crt"
server.ssl.key: "config/esnode1.key"
server.ssl.clientAuthentication: optional

# --------------------------------------------------------------------------------------------------------------------------------
# X-Pack features
# --------------------------------------------------------------------------------------------------------------------------------
# Note as of ES/Kibana 8 the xpack.security.enabled and other settings are enabled by default, and are removed from the yml file.
# Some components are still configurable, add them under this section if you wish to manage them.
xpack.reporting.enabled: true

#xpack.encryptedSavedObjects.encryptionKey: VALUE
#xpack.reporting.encryptionKey: VALUE
#xpack.security.encryptionKey: VALUE

# xpack.security.encryptionKey: "something_at_least_32_characters"

# enable PDF exporting via kibana
xpack.reporting.capture.browser.chromium.disableSandbox: true

xpack.security.session.idleTimeout: "30m"
xpack.security.session.lifespan: "7d"
xpack.security.session.cleanupInterval: "1d"