# Disable rules that conflict with Sphinx/MyST conventions
default: true

MD013: false  # Line length — Sphinx often has long code blocks / directives
MD033: false  # Inline HTML — needed for raw HTML and directives
MD041: false  # First line should be a heading — breaks for included partials
MD024: false  # Multiple headings with same content — Sphinx pages can reuse titles
MD034: false  # Bare URL — Sphinx cross-refs handle this
MD043: false  # Required heading structure — not needed for Sphinx TOC

# Optional fine-tuning
MD007:
  indent: 2    # Consistent list indentation
MD004:
  style: dash  # Consistent unordered list marker (-)
