FROM kibana:8.2.3

ARG KIBANA_HOME
ENV KIBANA_HOME=/usr/share/kibana

ENV PATH /usr/share/kibana/bin:$PATH

# Built from: https://github.com/elastic/dockerfiles/blob/v7.9.2/kibana/Dockerfile
USER root

#RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
#RUN curl -sL https://rpm.nodesource.com/setup_10.x | bash -
#RUN yum -y update

#RUN yum install -y unzip wget nodejs
RUN apt-get update 
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs npm wget unzip

USER kibana 

#################################### PLUGINS SECTION ####################################
# https://github.com/virusu/3D_kibana_charts_vis
RUN wget https://github.com/virusu/3D_kibana_charts_vis/archive/refs/heads/master.zip
RUN unzip master.zip -d 3D_kibana_charts_vis
RUN rm master.zip
RUN cd 3D_kibana_charts_vis
RUN npm install

# https://github.com/JuanCarniglia/area3d_vis 
RUN cd $KIBANA_HOME
RUN wget https://github.com/JuanCarniglia/area3d_vis/archive/refs/heads/master.zip
RUN unzip master.zip -d area3d_vis
RUN rm master.zip 
RUN cd area3d_vis
RUN npm install

#ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]

# CMD ["/usr/local/bin/kibana-docker"]