receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp:
    endpoint: data-prepper:21890
    tls:
      # Data Prepper source below uses plaintext in this dev profile.
      insecure: true
  debug:
    verbosity: basic

processors:
  batch: {}

extensions:
  health_check: {}

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
