name: docker-nifi-nginx

on:

  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]
    tags:
      - 'v*.*.*'

  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      working-directory: ./services/nginx

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: cogstacksystems/cogstack-nifi-nginx:latest

      - uses: actions/checkout@v2
      - name: Get and set release version env var
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: set docker release tag name
        if: "{{ contains(env.RELEASE_VERSION, 'master')}}"
        run: echo "RELEASE_VERSION=latest" >> $GITHUB_ENV

      - name: Output release tag version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Build and push Docker NiFi-Nginx image
        uses: docker/build-push-action@v2
        with:
          context : ./services/nginx
          file : "./services/nginx/Dockerfile"
          allow: network.host
          github-token: ${{ github.token }}
          tags: cogstacksystems/nifi-nginx:${{ env.RELEASE_VERSION }}
          push: true
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}