name: docker-elasticsearch-stack

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-22.04
          - platform: arm64
            runner: ubuntu-22.04-arm
    
    env:
      working-directory: ./services/elasticsearch

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cogstacksystems/kibana:latest

      - uses: actions/checkout@v3
      - name: Get and set release version env var
        id: release_version
        run: |
             echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
             echo "::set-output name=RELEASE_VERSION::$RELEASE_VERSION"
             
      - name: output test
        run: |
             echo ${{ env.RELEASE_VERSION }}
             echo $RELEASE_VERSION
             
      - name: set docker release tag name
        id: set_release_version
        if: ${{ env.RELEASE_VERSION != 'master' }}
        run: echo "RELEASE_VERSION=${RELEASE_VERSION#?}" >> $GITHUB_ENV

      - name: set docker release tag name
        id: set_release_version_latest
        if: ${{ env.RELEASE_VERSION == 'master' }}
        run: echo "RELEASE_VERSION=latest" >> $GITHUB_ENV
        
      - name: Output release tag version
        run: |
          echo $RELEASE_VERSION

      - name: Build and push Docker Kibana image
        run: |
          docker build --platform linux/${{ matrix.platform }} -t cogstacksystems/kibana:${{ env.RELEASE_VERSION }}-${{ matrix.platform }} -f "./services/kibana/Dockerfile_native" --build-arg CPU_ARCHITECTURE=${{ matrix.platform }} .
          docker push cogstacksystems/kibana:${{ env.RELEASE_VERSION }}-${{ matrix.platform }}

      - name: Build and push Docker Elasticsearch image
        run: |
          docker build --platform linux/${{ matrix.platform }} -t cogstacksystems/elasticsearch:${{ env.RELEASE_VERSION }}-${{ matrix.platform }} -f "./services/elasticsearch/Dockerfile_native" --build-arg CPU_ARCHITECTURE=${{ matrix.platform }} .
          docker push cogstacksystems/elasticsearch:${{ env.RELEASE_VERSION }}-${{ matrix.platform }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
