name: docker-dev-branch

on:

  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      working-directory: ./nifi

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: checkout repo
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cogstacksystems/cogstack-nifi:dev-latest
      
      - name: Build and push Docker NiFi image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context : ./nifi
          file : "./nifi/Dockerfile"
          allow: network.host
          github-token: ${{ github.token }}
          tags: cogstacksystems/cogstack-nifi:dev-latest
          push: true

      - name: Build and push Docker NiFi-Nginx image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context : ./services/nginx
          file : "./services/nginx/Dockerfile"
          allow: network.host
          github-token: ${{ github.token }}
          tags: cogstacksystems/nifi-nginx:dev-latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
