name: docker-elasticsearch-stack

on:
  push:
    branches: ['**']
    tags: ['v*.*.*']
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  elasticsearch:
    uses: ./.github/workflows/_docker-template.yml
    with:
      image: cogstacksystems/elasticsearch
      context: services/elasticsearch
      dockerfile: services/elasticsearch/Dockerfile_native
      cache_scope: elasticsearch
    secrets: inherit

  kibana:
    uses: ./.github/workflows/_docker-template.yml
    with:
      image: cogstacksystems/kibana
      context: services/kibana
      dockerfile: services/kibana/Dockerfile_native
      cache_scope: kibana
    secrets: inherit
